language: objective-c
osx_image: xcode8
xcode_project: SwifterSwift/SwifterSwift.xcodeproj
xcode_scheme: SwifterSwift
before_install:
  - gem install xcpretty
script:
    - xcodebuild -scheme 'Then-iOS' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty -c
    - xcodebuild -scheme 'Then-OSX' test | xcpretty -c
