language: objective-c
osx_image: xcode8
xcode_project: SwifterSwift/SwifterSwift.xcodeproj
before_install:
  - gem install xcpretty
script:
    - xcodebuild -scheme 'SwifterSwift iOS' -sdk iphonesimulator CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO test | xcpretty -c && xcodebuild -scheme 'SwifterSwift tvOS' -destination 'platform=tvOS Simulator,name=Apple TV 1080p' CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO test | xcpretty -c
