language: objective-c
osx_image: xcode8
xcode_project: SwifterSwift/SwifterSwift.xcodeproj
xcode_scheme: SwifterSwift
before_install:
  - gem install xcpretty
script:
  - set -o pipefail
  - xcodebuild -project $TRAVIS_XCODE_PROJECT -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK -destination 'name=iPhone 6' test | xcpretty -c
